### ISSUE TITLE
Question: Is the double-bang really required in WorkerActor Props.create()?

### ISSUE THREAD

**Issue by lestephane** [siudeks/hello-world-spring-kotlin-akka#1]
Why does this line require the double bang? I don't see what could possibly return a null reference...

```kotlin
fun props() = Props.create(WorkerActor::class.java) { WorkerActor() } !!
```
(source: https://github.com/siudeks/hello-world-spring-kotlin-akka/blob/master/src/main/kotlin/com/example/demo/WorkerActor.kt)

**Comment by siudeks** [comment]
In that particular case to make intellij happy :) 
(when no return type is defined, we see warning as below)
![image](https://user-images.githubusercontent.com/3256574/71307437-b9865a80-23ee-11ea-8f89-10c66aca0a77.png)

Alternatively we could define return type explicitly
fun props(): Props = Props.create(WorkerActor::class.java) { WorkerActor() }

**Comment by lestephane** [comment]
Strange, I'm not getting a warning when I remove them
